# api.http

### 查询订单的商品列表
GET http://localhost:8001/678mk6h56g456
### 减少商品库存
POST http://localhost:8001/decreaseNumber
Content-Type: application/json

[{"id":1, "name":"abc", "number":23},{"id":2, "name":"def", "number":11}]



### 获取用户
GET http://localhost:8101/8
### 增加积分
GET http://localhost:8101/8/score?score=1000



### 获取订单
GET http://localhost:8201/u564r327uyt
### 创建订单
GET http://localhost:8201/create


#################################################################################

### 查询订单的商品列表
GET http://localhost:3001/item-service/678mk6h56g456
### 查询订单的商品列表
GET http://localhost:3001/item-service/678mk6h56g456?token=y4ytg4t
### 减少商品库存
POST http://localhost:3001/item-service/decreaseNumber
Content-Type: application/json

[{"id":1, "name":"abc", "number":23},{"id":2, "name":"def", "number":11}]



### 获取用户
GET http://localhost:3001/user-service/8
### 增加积分
GET http://localhost:3001/user-service/8/score?score=1000



### 获取订单
GET http://localhost:3001/order-service/u564r327uyt
### 创建订单
GET http://localhost:3001/order-service/create







#################################################################################

### 查询订单的商品列表
GET http://localhost:3002/item-service/678mk6h56g456
### 查询订单的商品列表
GET http://localhost:3002/item-service/678mk6h56g456?token=y4ytg4t
### 减少商品库存
POST http://localhost:3002/item-service/decreaseNumber
Content-Type: application/json

[{"id":1, "name":"abc", "number":23},{"id":2, "name":"def", "number":11}]



### 获取用户
GET http://localhost:3002/user-service/8
### 增加积分
GET http://localhost:3002/user-service/8/score?score=1000



### 获取订单
GET http://localhost:3002/order-service/u564r327uyt
### 创建订单
GET http://localhost:3002/order-service/create