# item-service-dev.yml
# yml - yaml - yet another markup language
# 腋毛

# 向注册表注册的名字
spring:
  application:
    name: item-service
# item8001,  user8101,  order8201
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka