spring:
  application:
    name: user-service
# 8001, 8101, 8201
server:
  port: 8101

# 用户 Demo 数据
# [{id:7,u:aa,p:aa}, {id:8,...}, {9}]
sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},
             {\"id\":8, \"username\":\"def\",\"password\":\"456\"},
             {\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"
eureka:
  client:
    service-url:
      # defaultZone - 默认地点
      # 可以从云服务商购买不同地点的服务器
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

